# Generated by Django 6.0 on 2026-01-06 15:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thinker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Thinker name', max_length=50, validators=[django.core.validators.MinLengthValidator(1, 'Pleasee enter at least one character')])),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(db_index=True, help_text='Quote', max_length=2000, validators=[django.core.validators.MinLengthValidator(10, 'Pleasee enter at least ten characters')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('thinker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.thinker')),
            ],
        ),
    ]
