# Generated by Django 6.0 on 2026-01-06 16:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation', null=True, validators=[django.core.validators.MinLengthValidator(10, 'Please enter at least ten characters')]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(help_text='Quote', max_length=2000, validators=[django.core.validators.MinLengthValidator(10, 'Please enter at least ten characters')]),
        ),
        migrations.AlterField(
            model_name='thinker',
            name='name',
            field=models.CharField(help_text='Thinker name', max_length=50, validators=[django.core.validators.MinLengthValidator(1, 'Please enter at least one character')]),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Work name', max_length=50, validators=[django.core.validators.MinLengthValidator(1, 'Please enter at least one character')])),
                ('thinkers', models.ManyToManyField(to='content.thinker')),
            ],
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Thinker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.thinker')),
                ('Work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.work')),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.work'),
        ),
        migrations.AddField(
            model_name='thinker',
            name='works',
            field=models.ManyToManyField(to='content.work'),
        ),
    ]
