# Generated by Django 6.0 on 2026-01-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_quote_explanation_alter_quote_quote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thinker',
            name='works',
            field=models.ManyToManyField(blank=True, null=True, to='content.work'),
        ),
        migrations.AlterField(
            model_name='work',
            name='thinkers',
            field=models.ManyToManyField(blank=True, null=True, to='content.thinker'),
        ),
    ]
