# Generated by Django 6.0 on 2026-01-11 18:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_thinker_works_alter_work_thinkers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Picture name', max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(1, 'Please enter at least one character')])),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('content_type', models.CharField(blank=True, help_text='File type', max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='thinker',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='thinker',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='thinker',
            name='works',
            field=models.ManyToManyField(blank=True, to='content.work'),
        ),
        migrations.AlterField(
            model_name='work',
            name='thinkers',
            field=models.ManyToManyField(blank=True, to='content.thinker'),
        ),
        migrations.AddField(
            model_name='thinker',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.picture'),
        ),
    ]
