# Generated by Django 6.0 on 2026-01-21 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_picture_thinker_created_thinker_updated_work_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='work',
        ),
        migrations.AddField(
            model_name='quote',
            name='reference',
            field=models.CharField(blank=True, help_text='Reference', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(1, 'Please enter at least one character'), django.core.validators.MaxLengthValidator(100, 'Too many characters!')]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(help_text='Quote', max_length=2000, validators=[django.core.validators.MinLengthValidator(10, 'Please enter at least ten characters'), django.core.validators.MaxLengthValidator(2000, 'Too many characters!')]),
        ),
        migrations.AlterField(
            model_name='thinker',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
