# Generated by Django 6.0 on 2026-01-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_quote_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='user',
            new_name='created_by',
        ),
    ]
