# Generated by Django 6.0 on 2026-02-16 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_quote_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.quote')),
            ],
        ),
    ]
